[build]
command = "npm run build"
publish = "dist/"

[build.environment]
NODE_ENV = "production"
NPM_FLAGS = "--include=dev"

[[headers]]
for = "/*"

[headers.values]
access-control-allow-origin = "*"
